spring.application.name=demo
server.address=localhost
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringDemo
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=user_management

spring.flyway.schemas=user_management
spring.flyway.default-schema=user_management

spring.mvc.problemdetails.enabled=true

springdoc.swagger-ui.operationsSorter=method

jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCBkZW1v
jwt.expiration=86400000